general:
  encoder_pins: [14, 15, 18, 4, 26, 17, 27, 22, 19, 10, 9, 11, 13, 0, 5, 6]
  wall_switch_pins: [24, 25] # 00 -> idle, 10 -> sequence, 01 -> random
  service_button_pin: 23
  reboot_button_pin: 7
  charging_pin: 12
  led_pin: 8
  up: -1
  down: 1
  modes: [normal, manual, testing, scripts]

# test case specific configuration schema
testing_mode:
  c1: [8, 8, 3, 5] # [down counts, up counts, n times, pause duration]
  c2: [8, 8, 3, 3] # [down counts, up counts, n times, pause duration]

# sequence specific configuration schema
sequences:
  random_params: [0.4, 0.6] # [min (0-1), max (0-1)]
  wave_params: [0.1, 0.2, 0.5, 0.5] # [amplitude (0-1), translation (0-1), frequency (0-1), step (0-1)]
  alternating_params: [0.1, 0.4] # [amplitude (0-1), translation (0-1)]

# base env configuration schema
environment_specific_config: &default_env_config
  debug: true # debug mode (suppresses  some logs)
  max_counts: 80 # max number of counts to move
  n_motors: 16 # number of motors
  suppress_count_logging: false # suppresses count logging to console
  disabled_motors: [] # motors to disable at start (can be recovered later)
  dead_motors: [] # motors that are dead (cannot be recovered)

  # states
  random_state_duration: 3600 # time before switching to idle mode (seconds: 3600 = 1 hour)
  sequence_state_duration: 3600 # time before switching back to idle mode (seconds: 3600 = 1 hour)
  duration_before_recalibration: 4000 # time before recalibrating counts (seconds) - set higher than other durations to effectively ignore recalibration

  # charging
  candles_per_charge_cycle: 2
  charge_cycle_time: 900 # charging time (in seconds: 900 = 15 min)
  available_charging_hours: [0] # Midnight (24hr)

  # motors
  throttle_offset: 0.04 # offset from neutral throttle in both directions (defines base speed)
  uncalibrated_up_throttle: 0 # uncalibrated throttle when moving up
  uncalibrated_down_throttle: 0.3 # uncalibrated throttle when moving down
  max_recovery_attempts: 2 # max number of times to attempt to recover a motor before marking as dead
  recovery_counts: 8 # number of counts to move when attempting to recover
  default_allowable_down_cps: 0.4 # falls below this value when moving down -> motor is considered stalled
  default_allowable_up_cps: 0.3 # falls below this value when moving up -> motor is considered stalled

  # calibration
  calibration_counts: 8 # distance to move for calibration (in counts)
  calibration_file_path: calibrations.json # file to store calibration data
  skip_find_home: false # don't attempt to find home, assume already found (should only be used when candles are disconnected)

development:
  <<: *default_env_config
  debug: true
  suppress_count_logging: false
  calibration_file_path: calibrations_dev.json
  disabled_motors: []
  dead_motors: [9]
  available_charging_hours: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
  skip_find_home: false
production:
  <<: *default_env_config
  debug: false
  calibration_file_path: calibrations.json
  suppress_count_logging: true
testing:
  <<: *default_env_config
  disabled_motors: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  calibration_file_path: calibrations_test.json
  random_state_duration: 60 # 1 minute
  sequence_state_duration: 60 # 1 minute
  charge_cycle_time: 10
  available_charging_hours: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
  skip_find_home: true
