# general configuration schema, applied to all environments
general:
  encoder_pins: [14, 15, 18, 4, 26, 17, 27, 22, 19, 10, 9, 11, 13, 0, 5, 6]
  wall_switch_pins: [24, 25] # 00 -> idle, 10 -> sequence, 01 -> random
  service_button_pin: 23
  reboot_button_pin: 7
  charging_pin: 12
  led_pin: 8
  up: -1
  down: 1
  modes: [normal, manual, scripts, testing]

# base env configuration schema
environment_specific_config: &default_env_config
  debug: true
  max_counts: 30
  n_motors: 16
  suppress_count_logging: false
  initial_disabled_motors: []

  # states
  random_state_duration: 3600 # 1 hour
  sequence_state_duration: 3600 # 1 hour

  # charging
  candles_per_charge_cycle: 2
  charge_cycle_time: 600
  available_charging_hours: [1] # 1 o'clock (24hr) # todo: will likely be removed (new system)

  # motors
  throttle_offset: 0.04 # offset from neutral throttle in both directions (defines base speed)
  uncalibrated_up_throttle: 0 # uncalibrated throttle when moving up
  uncalibrated_down_throttle: 0.3 # uncalibrated throttle when moving down

  # timeouts
  to_home_timeout: 180 # max timeout (seconds) for trying to move home (disables motor if reached)
  to_position_timeout: 180 # max timeout (seconds) for trying to move to a position (disables motor if reached)
  calibrate_relative_throttle_timeout: 30 # max timeout (seconds) when calibrating
  calibrate_cps_timeout: 30 # max timeout (seconds) when calibrating cps
  calibrate_neutral_timeout: 5 # max timeout (seconds) when calibrating
  unknown_position_timeout: 60 # max timeout (seconds) when trying to find home from unknown position
  max_time_between_encoder_readings: 10 # max time (seconds) between encoder readings before disabling
  unknown_max_time_between_encoder_readings: 3 # max time (seconds) between encoder readings when trying to find home from unknown position

  # calibration
  calibration_counts: 8 # distance to move for calibration (in counts)
  calibration_file_path: calibrations.json # file to store calibration data
  skip_find_home: false # don't attempt to find home, assume already found (should only be used when candles are disconnected)

development:
  <<: *default_env_config
  calibration_file_path: calibrations_dev.json # file to store calibration data
  initial_disabled_motors: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  calibrate_neutral_timeout: 3
  skip_find_home: true
  suppress_count_logging: true
production:
  <<: *default_env_config
  debug: false
  suppress_count_logging: true
testing:
  <<: *default_env_config
  calibration_file_path: calibrations_test.json # file to store calibration data
  random_state_duration: 60 # 1 minute
  sequence_state_duration: 60 # 1 minute
  charge_cycle_time: 10
  available_charging_hours: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
  skip_find_home: true
